### ISSUE TITLE
Failed to start the game

### ISSUE THREAD

**Issue by mquinson** [VanessaE/dreambuilder_game#9] opened 2015-08-21 00:24 UTC
Hello, (disclamer: I'm a minetest noob).

I cloned your repo with all subrepos in my ~/.minetest/games and tried to start the game, but it fails with that error message:

2015-08-21 02:19:17: ERROR[main]: Failed to load and run script from 
2015-08-21 02:19:17: ERROR[main]: /home/mquinson/.minetest/games/dreambuilder_game/mods/plantlife_modpack/3dmushrooms/init.lua:
2015-08-21 02:19:17: ERROR[main]: ...der_game/mods/plantlife_modpack/3dmushrooms/init.lua:8: Attempt to override non-existent item flowers:mushroom_fertile_brown
2015-08-21 02:19:17: ERROR[main]: stack traceback:
2015-08-21 02:19:17: ERROR[main]: 	[C]: in function 'error'
2015-08-21 02:19:17: ERROR[main]: 	/usr/share/games/minetest/builtin/game/register.lua:324: in function 'override_item'
2015-08-21 02:19:17: ERROR[main]: 	...der_game/mods/plantlife_modpack/3dmushrooms/init.lua:8: in main chunk

(minetest 0.4.13)

I understand that this bug is in plantlife_modpack, but the problem still makes your game unusable for me. Thanks for the game anyway. Please help me enjoying it for real.

**Comment by VanessaE** [comment] 2015-08-21 01:47
This is not a bug.  Rather, you've pulled in a copy of Plantlife from somewhere (maybe my mainline repo) that is too *new* for Dreambuilder to run.

I will be updating Dreambuilder's code to work with it soon (indeed, I'll update plantlife then, as well).  

Meanwhile, stick with the copy that comes with Dreambuilder.  If necessary, download and use [my official release tarball](http://digitalaudioconcepts.com/vanessa/hobbies/minetest/Dreambuilder_Game.tar.bz2) instead of cloning from git (not sure why a clone is pulling in newer copies of those submodules than what I last committed).

**Closed by VanessaE** 2015-08-21 01:47 UTC
Labels: notabug

**Comment by mquinson** [comment] 2015-08-21 07:55
Ok, thanks for the link. From your forum post, I followed the github link because I wanted to have a look at your code before downloading, and from there there was no mention of the tarball anymore.

I guess you should add a mention of it to the README of your git or something.

Thanks again, Mt
